### ISSUE TITLE
All routes in demo repo through traefik

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Demo.Simple#110]
## Description
As a developer I want a simple to understand and debug demo

## Acceptance criteria

- [ ] Ports for ipfs, matrix, playground server all routed through traefik
- [ ] Ports that are routed through traefik are not exposed on individual containers, only on traefik container

**Comment by techsmyth** [comment]
Duplicate?

**Comment by valentinyanakiev** [comment]
duplicate
