### ISSUE TITLE
Refresh demo repo 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Demo.Simple#127]
## Description
As a new developer I want to be able to see the new user interface with canvases

## Acceptance criteria

- [ ] Demo repo updated to have the following image versions: server 0.17.0, client 0.13.0, client-lib + populator latest
- [ ] Population using sample data runs without errors
- [ ] Flags set as follows: Subscriptions=false, notification=false, canvases=true, communications=true, communications-discussions=true

**Comment by Comoque1** [comment]
After exploring the updates, the findings are as follows:

- [x] Demo repo updated to have the following image versions: server 0.16.0, client 0.12.1, client-lib + populator latest
  - [ ] server - v0.16.1 (same as PROD version)
  - [ ] client-web - v0.12.3p2 (same as PROD version)
- [x] Population using sample data runs without errors - **OK**
- [ ] Flags set as follows: Subscriptions=false, notification=false, canvases=true, communications=true, communications-discussions=true - **notification=true**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9d3afb31-3acb-450d-8047-cdd2fef431d2)
- [ ] Tags on repository mention **cherrytwist**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fb97f013-f0c4-40cc-9f91-0edcfe31beb4)

**Comment by valentinyanakiev** [comment]
Changing AC to be using the versions we will release for Kratos 0.8.0.
