### ISSUE TITLE
Errors while populating the server with data

### ISSUE THREAD

**Issue by acirep** [cherrytwist/Demo.Simple#90]
**Describe the bug**
`npm run sample-data` is working but some errors reported as DTO validation fails for class UserInput

**To Reproduce**
1. Follow setup guide
2. run `npm run sample-data`
3. See errors while data is being imported

**Expected behavior**
Uhm, no errors? ;-)

**Screenshots**
> info: ... added user to group: Jedis
> info: [255] - Processing user: Shona Malcolm Swiggs ...
> info: ===> userCreation - FULL {"durationMs":796}
> error: Could not create user: DTO validation for class UserInput {
> } failed! An instance of UserInput has failed the validation:
>  - property email has failed the following constraints: isEmail 
> 
> info: [255] - Processing user: Iola Marx ...
> info: userCreation {"durationMs":5}
> info: ... created user: Iola Marx
> info: ... added user to group: Jedis
> info: [256] - Processing user: Ozie Bobby .
> .
> .
> .
> info: [388] - Processing user: Sung Carman ...
> info: userCreation {"durationMs":486}
> info: ... created user: Sung Carman
> info: [389] - Processing user: Avelina Rickey ...
> info: ===> userCreation - FULL {"durationMs":687}
> info: userCreation {"durationMs":468}
> info: ... created user: Avelina Rickey
> info: [390] - Processing user: Dino Fendlow Chi ...
> error: Could not create user: DTO validation for class UserInput {
> } failed! An instance of UserInput has failed the validation:
>  - property email has failed the following constraints: isEmail 
> 
> info: [390] - Processing user: Thea Clemerson Shelia ...
> info: ===> userCreation - FULL {"durationMs":7}
> info: userCreation {"durationMs":7}
> error: Could not create user: DTO validation for class UserInput {
> } failed! An instance of UserInput has failed the validation:
>  - property email has failed the following constraints: isEmail

**Comment by techsmyth** [comment]
Thanks for the feedback, the set of users in the demo indeed had some issues in the data. Also to be honest way to many sample users in there - so just reduced to 100 sample users.

The following PR has the update  https://github.com/cherrytwist/Demo/pull/91 if you want to give that a try?

Cheers, Neil

**Comment by acirep** [comment]
Tested and this fix removes errors, thanks

**Comment by techsmyth** [comment]
Thanks for verifying 👍

Out of curiosity, what brought you to CT?
